# render.yaml
services:
    - name: nextjs-web
      type: web
      env: node
      region: oregon # Change as needed
      plan: free # Or 'starter', 'standard', etc.
      buildCommand: sudo npm install --legacy-peer-deps && sudo npm run build
      startCommand: npm start
      autoDeploy: true
      envVars:
        - key: NODE_ENV
          value: production
        - key: DATABASE_URL
          fromDatabase:
            name: nextjs-db
            property: postgresql://aichat:gjS78wKYB30wv5oktrif5xNYmMNi8GPS@dpg-ct1mgam8ii6s73fhctrg-a.oregon-postgres.render.com/aichat_mair?sslmode=require
        - key: NEXT_PUBLIC_API_URL
          value: https://ai-chatbot-dusd.onrender.com