# render.yaml
services:
    - name: nextjs-web
      type: web
      env: node
      region: oregon # Change as needed
      plan: free # Or 'starter', 'standard', etc.
      buildCommand: npm install && npm run build
      startCommand: npm start
      autoDeploy: true
      envVars:
        - key: NODE_ENV
          value: production
        - key: DATABASE_URL
          fromDatabase:
            name: nextjs-db
            property: connectionString
        - key: NEXT_PUBLIC_API_URL
          value: https://<your-render-service-name>.onrender.com
        - key: SSL
          value: true
  
  databases:
    - name: nextjs-db
      plan: free # Use 'starter' or higher for production
      region: oregon # Match the region of the web service
      postgresVersion: 15 # Specify the desired PostgreSQL version
      diskSize: 1GB  